# Generated by Django 4.2.8 on 2024-12-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_wizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
                ('sidenavi', models.TextField(max_length=100)),
                ('topnavi', models.TextField(max_length=100)),
                ('authtype', models.CharField(blank=True, choices=[('sss', '세션'), ('TKN', '토큰')], max_length=3, null=True)),
                ('template', models.CharField(blank=True, choices=[('doc', '닥터리스')], max_length=3, null=True)),
            ],
        ),
    ]
